site_name: Monad STD Document
site_author: Embers-of-the-Fire
site_description: Api documentation for monad_std
repo_url: https://github.com/Embers-of-the-Fire/monad-std/
repo_name: Embers-of-the-Fire/monad_std
copyright: Copyright &copy; 2023 Embers-of-the-Fire
edit_uri: edit/main/docs_src/
markdown_extensions:
  - md_in_html
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - abbr
extra_javascript:
  - init.js
nav:
  - Introduction: index.md
  - Quick Start: "quick_start.md"
  - Api:
      - "api_document/api_overview.md"
      - "api_document/option.md"
      - "api_document/result.md"
      - "api_document/error.md"
      - "api_document/iterator_tools.md"
      - "api_document/std_types.md"
      - "api_document/iterator_tools_impl.md"
      - "api_document/option_impl.md"
      - "api_document/result_impl.md"
      - "api_document/typedef.md"
      - Utilities:
          - "api_document/utils/cmp.md"
  - Change Log: CHANGELOG.md
theme:
  name: material
  language: 'en'
  feature:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - navigation.tabs
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.path
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          paths: ['..']
          options:
            show_root_heading: true
            show_source: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            heading_level: 1
  # - git-committers:
  #     repository: Embers-of-the-Fire/monad_std
  #     branch: main
  # - git-authors