site_name: Monad STD Document
site_author: Embers-of-the-Fire
site_description: Api documentation for monad_std
copyright: Copyright &copy; 2023 Embers-of-the-Fire
markdown_extensions:
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - abbr
extra_javascript:
  - init.js
nav:
  - Intro:
    - Intro: index.md
  - Api:
    - "Api Document/option.md"
    - "Api Document/result.md"
    - "Api Document/Result-Impl.md"
theme:
  name: material
  language: 'en'
  feature:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.path
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          paths: ['..']
          options:
            show_root_heading: false
            show_source: false
            heading_level: 2