name: Upload code coverage
on:
  push:
  pull_request:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
      - name: Install project dependencies
        run: |
          poetry install
      - name: Calculate code coverage
        run: |
          poetry run pytest --cov=monad_std --cov-report=json tests/
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.json,!./cache
          fail_ci_if_error: true